import http from "node:http";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(here, "..");
const staticRoot = path.join(projectRoot, "dist");
const dataRoot = path.join(projectRoot, "data");
const uploadRoot = path.join(dataRoot, "uploads");
const dbFile = path.join(dataRoot, "db.json");
const port = Number(process.env.PORT || 4173);
const publicUrl = process.env.PUBLIC_URL || `http://127.0.0.1:${port}`;
const allowOrigin = process.env.ALLOW_ORIGIN || "*";

const cities = ["Bakı", "Gəncə", "Sumqayıt", "Şəki", "Lənkəran", "Naxçıvan", "Quba", "Mingəçevir"];
const seedProducts = [
  { id: "p1", title: "Klassik denim gödəkçə", store: "NOVA Studio", category: "Geyim", subtype: "Gödəkçə", material: "Denim", colors: ["Mavi"], sizes: ["S", "M", "L", "XL"], price: 89, stock: 8, city: "Bakı", image: "https://images.unsplash.com/photo-1708523842501-1619478cea1f?auto=format&fit=crop&w=900&q=85", badge: "Seçimimiz", description: "Yumşaq denim parçadan hazırlanmış, hər mövsümə uyğun klassik gödəkçə." },
  { id: "p2", title: "Ağ basic köynək", store: "Mimoza", category: "Geyim", subtype: "T-shirt", material: "Pambıq", colors: ["Ağ", "Qara"], sizes: ["S", "M", "L"], price: 32, stock: 20, city: "Bakı", image: "https://images.unsplash.com/photo-1467043237213-65f2da53396f?auto=format&fit=crop&w=900&q=85", description: "Gündəlik kombinlərin əvəzolunmazı. 100% nəfəs alan pambıq." },
  { id: "p3", title: "Air Street 02", store: "Step Lab", category: "Ayaqqabı", subtype: "İdman ayaqqabısı", material: "Dəri", colors: ["Qara", "Ağ"], sizes: ["38", "39", "40", "41"], price: 145, stock: 5, city: "Gəncə", image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85", badge: "Yeni", description: "Şəhər ritmi üçün yüngül altlıq və yumşaq içlik." },
  { id: "p4", title: "Kətan oversize köynək", store: "Sahil Concept", category: "Geyim", subtype: "Köynək", material: "Kətan", colors: ["Bej", "Yaşıl"], sizes: ["M", "L", "XL"], price: 64, stock: 12, city: "Bakı", image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=85", description: "Yay üçün yüngül və rahat kətan köynək." },
  { id: "p5", title: "Luna gündəlik çanta", store: "Mavi Room", category: "Çanta", subtype: "Çiyin çantası", material: "Dəri", colors: ["Bej", "Qara"], sizes: ["One size"], price: 118, stock: 4, city: "Sumqayıt", image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85", description: "Kiçik ölçüdə böyük rahatlıq. Gündəlik əşyaların üçün ideal." },
  { id: "p6", title: "Minimal saat 36 mm", store: "Saatçı", category: "Aksesuar", subtype: "Saat", material: "Paslanmayan polad", colors: ["Ağ"], sizes: ["One size"], price: 96, stock: 6, city: "Bakı", image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=85", description: "Minimal siferblat, klassik qayış və hər günə uyğun görünüş." },
  { id: "p7", title: "Terracotta sviter", store: "Mimoza", category: "Geyim", subtype: "Sviter", material: "Yun", colors: ["Yaşıl", "Bej"], sizes: ["S", "M", "L"], price: 74, stock: 10, city: "Şəki", image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=85", description: "Sərin günlər üçün isti və yumşaq toxunuş." },
  { id: "p8", title: "Sakitlik şamı", store: "Evə", category: "Ev & həyat", subtype: "Dekor", material: "Soya mumu", colors: ["Ağ"], sizes: ["One size"], price: 28, stock: 25, city: "Lənkəran", image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=900&q=85", badge: "Yerli istehsal", description: "Evinə sakit bir qoxu və isti işıq əlavə et." },
  { id: "p9", title: "Qara straight jeans", store: "Denim Co", category: "Geyim", subtype: "Jeans", material: "Denim", colors: ["Qara"], sizes: ["28", "30", "32", "34"], price: 78, stock: 9, city: "Bakı", image: "https://images.unsplash.com/photo-1708523842501-1619478cea1f?auto=format&fit=crop&w=900&q=85", badge: "Trend", description: "Gündəlik üslub üçün rahat kəsim, tünd qara denim." }
];

fs.mkdirSync(uploadRoot, { recursive: true });
function now() { return new Date().toISOString(); }
function id(prefix) { return `${prefix}_${crypto.randomUUID()}`; }
function hash(value) { return crypto.createHash("sha256").update(value).digest("hex"); }
function readJson(file, fallback) { try { return JSON.parse(fs.readFileSync(file, "utf8")); } catch { return fallback; } }
function writeJson(file, value) { const temp = `${file}.tmp`; fs.writeFileSync(temp, JSON.stringify(value, null, 2)); fs.renameSync(temp, file); }
function initialDb() { return { users: [], sessions: [], otpChallenges: [], stores: [], products: seedProducts, orders: [] }; }
let db = readJson(dbFile, initialDb());
for (const key of ["users", "sessions", "otpChallenges", "stores", "products", "orders"]) if (!Array.isArray(db[key])) db[key] = [];
if (!db.products.length) db.products = seedProducts;
const photoByProduct = Object.fromEntries(seedProducts.map(product => [product.id, product.image]));
for (const product of db.products) if (product.id in photoByProduct && typeof product.image === "string" && product.image.startsWith("/assets/")) product.image = photoByProduct[product.id];
writeJson(dbFile, db);

const types = { ".html": "text/html; charset=utf-8", ".css": "text/css; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".svg": "image/svg+xml", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png", ".webp": "image/webp", ".json": "application/json" };
function headers(extra = {}) { return { "Access-Control-Allow-Origin": allowOrigin, "Access-Control-Allow-Headers": "Content-Type, Authorization", "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS", "Cache-Control": "no-store", ...extra }; }
function send(res, status, body, extra = {}) { const payload = typeof body === "string" ? body : JSON.stringify(body); res.writeHead(status, headers({ "Content-Type": typeof body === "string" ? "text/plain; charset=utf-8" : "application/json; charset=utf-8", ...extra })); res.end(payload); }
function readBody(req, limit = 15 * 1024 * 1024) { return new Promise((resolve, reject) => { let body = ""; req.on("data", chunk => { body += chunk; if (body.length > limit) { reject(new Error("Payload çox böyükdür")); req.destroy(); } }); req.on("end", () => { try { resolve(body ? JSON.parse(body) : {}); } catch { reject(new Error("JSON məlumatı düzgün deyil")); } }); req.on("error", reject); }); }
function bearer(req) { const value = req.headers.authorization || ""; return value.startsWith("Bearer ") ? value.slice(7) : ""; }
function getUser(req) { const token = bearer(req); const session = db.sessions.find(item => item.token === token && item.expiresAt > Date.now()); return session ? db.users.find(user => user.id === session.userId) : null; }
function requireUser(req, res) { const user = getUser(req); if (!user) { send(res, 401, { error: "Giriş tələb olunur" }); return null; } return user; }
function normalizeIdentifier(value) { const raw = String(value || "").trim(); if (raw.includes("@")) return { value: raw.toLowerCase(), type: "email" }; const phone = raw.replace(/[^0-9+]/g, ""); return { value: phone.startsWith("+") ? phone : `+${phone}`, type: "sms" }; }
async function deliverOtp(identifier, code) {
  if (identifier.type === "email" && process.env.RESEND_API_KEY) { const response = await fetch("https://api.resend.com/emails", { method: "POST", headers: { Authorization: `Bearer ${process.env.RESEND_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify({ from: process.env.RESEND_FROM || "Yerli <onboarding@resend.dev>", to: [identifier.value], subject: "Yerli giriş kodun", html: `<p>Yerli giriş kodun: <strong>${code}</strong></p><p>Kod 10 dəqiqə ərzində keçərlidir.</p>` }) }); if (!response.ok) throw new Error("Email OTP göndərilmədi"); return "email"; }
  if (identifier.type === "sms" && process.env.TWILIO_ACCOUNT_SID && process.env.TWILIO_AUTH_TOKEN && process.env.TWILIO_FROM) { const params = new URLSearchParams({ To: identifier.value, From: process.env.TWILIO_FROM, Body: `Yerli giriş kodun: ${code}. Kod 10 dəqiqə keçərlidir.` }); const auth = Buffer.from(`${process.env.TWILIO_ACCOUNT_SID}:${process.env.TWILIO_AUTH_TOKEN}`).toString("base64"); const response = await fetch(`https://api.twilio.com/2010-04-01/Accounts/${process.env.TWILIO_ACCOUNT_SID}/Messages.json`, { method: "POST", headers: { Authorization: `Basic ${auth}`, "Content-Type": "application/x-www-form-urlencoded" }, body: params }); if (!response.ok) throw new Error("SMS OTP göndərilmədi"); return "sms"; }
  if (process.env.NODE_ENV === "production" && process.env.DEV_OTP !== "true") throw new Error("OTP provayderi konfiqurasiya edilməyib");
  return "preview";
}
function saveDataUrl(dataUrl, filename = "image.bin") { const match = String(dataUrl || "").match(/^data:(image\/(?:png|jpeg|jpg|webp|svg\+xml));base64,(.+)$/); if (!match) throw new Error("Yalnız PNG, JPG, WEBP və SVG şəkilləri dəstəklənir"); const ext = match[1].includes("png") ? "png" : match[1].includes("webp") ? "webp" : match[1].includes("svg") ? "svg" : "jpg"; const bytes = Buffer.from(match[2], "base64"); if (bytes.length > 10 * 1024 * 1024) throw new Error("Şəkil 10 MB-dan kiçik olmalıdır"); const safe = path.basename(filename).replace(/[^a-z0-9._-]/gi, "-").slice(0, 80); const fileName = `${Date.now()}-${crypto.randomUUID()}-${safe || "image"}.${ext}`; fs.writeFileSync(path.join(uploadRoot, fileName), bytes); return `/media/${fileName}`; }
async function processImage(dataUrl, filename) { if (process.env.REMOVEBG_API_KEY) { const match = String(dataUrl || "").match(/^data:(image\/[^;]+);base64,(.+)$/); if (!match) throw new Error("Şəkil məlumatı düzgün deyil"); const form = new FormData(); form.append("image_file", new Blob([Buffer.from(match[2], "base64")], { type: match[1] }), filename || "product.jpg"); form.append("size", "auto"); const response = await fetch("https://api.remove.bg/v1.0/removebg", { method: "POST", headers: { "X-Api-Key": process.env.REMOVEBG_API_KEY }, body: form }); if (!response.ok) throw new Error("Background removal servisi cavab vermədi"); const output = Buffer.from(await response.arrayBuffer()); const outputName = `${Date.now()}-${crypto.randomUUID()}-processed.png`; fs.writeFileSync(path.join(uploadRoot, outputName), output); return { processedUrl: `/media/${outputName}`, provider: "remove.bg" }; } return { processedUrl: saveDataUrl(dataUrl, `processed-${filename || "image"}`), provider: "server-storage" }; }
function cartItems(items = []) { return items.map(item => { const product = db.products.find(productItem => productItem.id === item.productId); if (!product) throw new Error("Məhsul tapılmadı"); const quantity = Math.max(1, Math.min(99, Number(item.quantity || 1))); return { productId: product.id, title: product.title, store: product.store, quantity, unitPrice: Number(product.price), selectedColor: item.selectedColor || product.colors?.[0] || "", selectedSize: item.selectedSize || product.sizes?.[0] || "" }; }); }
function shippingQuote(shipping = {}) { const city = String(shipping.city || "Bakı"); const amount = city === "Bakı" ? 3.5 : cities.includes(city) ? 6 : 8; return { method: "Yerli kuryer", city, amount, etaDays: city === "Bakı" ? "1-2" : "2-4", currency: "AZN" }; }
async function stripeCheckout(order, requestUrl) { if (!process.env.STRIPE_SECRET_KEY || order.payment.method !== "card") return null; const params = new URLSearchParams(); params.set("mode", "payment"); params.set("success_url", `${process.env.PUBLIC_URL || new URL(requestUrl).origin}/?order=${order.id}&status=success`); params.set("cancel_url", `${process.env.PUBLIC_URL || new URL(requestUrl).origin}/?order=${order.id}&status=cancelled`); order.items.forEach((item, index) => { params.set(`line_items[${index}][quantity]`, String(item.quantity)); params.set(`line_items[${index}][price_data][currency]`, "azn"); params.set(`line_items[${index}][price_data][unit_amount]`, String(Math.round(item.unitPrice * 100))); params.set(`line_items[${index}][price_data][product_data][name]`, item.title); }); const response = await fetch("https://api.stripe.com/v1/checkout/sessions", { method: "POST", headers: { Authorization: `Bearer ${process.env.STRIPE_SECRET_KEY}`, "Content-Type": "application/x-www-form-urlencoded" }, body: params }); if (!response.ok) throw new Error("Kart ödənişi sessiyası yaradıla bilmədi"); const session = await response.json(); return { id: session.id, url: session.url }; }

async function api(req, res, pathname, requestUrl) {
  if (pathname === "/api/health" && req.method === "GET") return send(res, 200, { ok: true, service: "yerli-api", time: now() });
  if (pathname === "/api/products" && req.method === "GET") return send(res, 200, { products: db.products, stores: db.stores });
  if (pathname === "/api/auth/request-otp" && req.method === "POST") { const body = await readBody(req, 10000); const identifier = normalizeIdentifier(body.identifier); if ((identifier.type === "email" && !/^\S+@\S+\.\S+$/.test(identifier.value)) || (identifier.type === "sms" && identifier.value.replace(/\D/g, "").length < 10)) return send(res, 400, { error: "Email və ya telefon nömrəsini düzgün yaz" }); const code = String(crypto.randomInt(100000, 1000000)); const channel = await deliverOtp(identifier, code); db.otpChallenges = db.otpChallenges.filter(item => item.expiresAt > Date.now() && item.identifier !== identifier.value); db.otpChallenges.push({ id: id("otp"), identifier: identifier.value, type: identifier.type, codeHash: hash(code), attempts: 0, expiresAt: Date.now() + 10 * 60 * 1000 }); writeJson(dbFile, db); const response = { ok: true, channel: channel === "preview" ? identifier.type : channel, expiresIn: 600 }; if (channel === "preview") response.devCode = code; return send(res, 200, response); }
  if (pathname === "/api/auth/verify-otp" && req.method === "POST") { const body = await readBody(req, 10000); const identifier = normalizeIdentifier(body.identifier); const challenge = db.otpChallenges.find(item => item.identifier === identifier.value && item.expiresAt > Date.now()); if (!challenge || challenge.attempts >= 5 || hash(String(body.code || "")) !== challenge.codeHash) { if (challenge) { challenge.attempts += 1; writeJson(dbFile, db); } return send(res, 400, { error: "Giriş kodu düzgün deyil və ya vaxtı bitib" }); } db.otpChallenges = db.otpChallenges.filter(item => item.id !== challenge.id); let user = db.users.find(item => item.identifier === identifier.value); if (!user) { user = { id: id("user"), identifier: identifier.value, identifierType: identifier.type, createdAt: now() }; db.users.push(user); } const token = crypto.randomBytes(32).toString("hex"); db.sessions.push({ token, userId: user.id, expiresAt: Date.now() + 30 * 24 * 60 * 60 * 1000 }); writeJson(dbFile, db); return send(res, 200, { token, user: { id: user.id, identifier: user.identifier, identifierType: user.identifierType }, store: db.stores.find(item => item.ownerId === user.id) || null }); }
  if (pathname === "/api/auth/me" && req.method === "GET") { const user = getUser(req); return user ? send(res, 200, { user, store: db.stores.find(item => item.ownerId === user.id) || null }) : send(res, 401, { error: "Giriş tələb olunur" }); }
  if (pathname === "/api/auth/logout" && req.method === "POST") { const token = bearer(req); db.sessions = db.sessions.filter(item => item.token !== token); writeJson(dbFile, db); return send(res, 200, { ok: true }); }
  if (pathname === "/api/stores" && req.method === "POST") { const user = requireUser(req, res); if (!user) return; const body = await readBody(req); if (!body.name || !body.city || !body.phone) return send(res, 400, { error: "Mağaza adı, şəhər və əlaqə nömrəsi tələb olunur" }); let store = db.stores.find(item => item.ownerId === user.id); if (!store) { store = { id: id("store"), ownerId: user.id, createdAt: now() }; db.stores.push(store); } Object.assign(store, { name: String(body.name).trim(), owner: String(body.owner || "").trim(), city: body.city, phone: String(body.phone).trim(), description: String(body.description || "").trim(), updatedAt: now() }); writeJson(dbFile, db); return send(res, 200, { store }); }
  if (pathname === "/api/media/process" && req.method === "POST") { const user = requireUser(req, res); if (!user) return; const body = await readBody(req); const originalUrl = saveDataUrl(body.dataUrl, body.fileName); const result = await processImage(body.dataUrl, body.fileName); return send(res, 200, { originalUrl, ...result }); }
  if (pathname === "/api/products" && req.method === "POST") { const user = requireUser(req, res); if (!user) return; const store = db.stores.find(item => item.ownerId === user.id); if (!store) return send(res, 400, { error: "Əvvəl mağaza profilini tamamla" }); const body = await readBody(req); if (!body.title || !body.category || Number(body.price) <= 0) return send(res, 400, { error: "Başlıq, kateqoriya və qiymət tələb olunur" }); const product = { id: id("product"), title: String(body.title).trim(), store: store.name, storeId: store.id, category: body.category, subtype: String(body.subtype || "").trim(), material: String(body.material || "").trim(), colors: Array.isArray(body.colors) ? body.colors : [], sizes: Array.isArray(body.sizes) ? body.sizes : [], price: Number(body.price), stock: Number(body.stock || 0), city: store.city, image: body.originalUrl || "", aiProcessed: body.processedUrl || body.originalUrl || "", description: String(body.description || `${store.name} mağazasından yeni məhsul.`), createdAt: now() }; db.products.push(product); writeJson(dbFile, db); return send(res, 201, { product }); }
  if (pathname === "/api/shipping/quote" && req.method === "POST") { const body = await readBody(req); return send(res, 200, { quote: shippingQuote(body.shipping || {}) }); }
  if (pathname === "/api/orders" && req.method === "POST") { const user = requireUser(req, res); if (!user) return; const body = await readBody(req); const items = cartItems(body.items); if (!items.length) return send(res, 400, { error: "Sifariş üçün səbət boş olmamalıdır" }); const shipping = { ...(body.shipping || {}), ...shippingQuote(body.shipping || {}) }; const subtotal = items.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0); const order = { id: id("order"), userId: user.id, items, subtotal, shipping, total: subtotal + shipping.amount, payment: { method: body.payment?.method || "cash", status: body.payment?.method === "card" ? "pending" : "cash_on_delivery" }, customer: { name: String(body.customer?.name || "").trim(), phone: String(body.customer?.phone || user.identifier).trim(), note: String(body.customer?.note || "").trim() }, status: "new", createdAt: now() }; order.paymentSession = await stripeCheckout(order, requestUrl); if (order.paymentSession) order.payment.status = "checkout_created"; db.orders.push(order); writeJson(dbFile, db); return send(res, 201, { order, checkoutUrl: order.paymentSession?.url || null }); }
  if (pathname === "/api/orders" && req.method === "GET") { const user = requireUser(req, res); if (!user) return; return send(res, 200, { orders: db.orders.filter(item => item.userId === user.id) }); }
  return send(res, 404, { error: "API endpoint tapılmadı" });
}

const server = http.createServer(async (req, res) => {
  const requestUrl = new URL(req.url, `http://${req.headers.host || "127.0.0.1"}`); const pathname = decodeURIComponent(requestUrl.pathname);
  if (req.method === "OPTIONS") { res.writeHead(204, headers()); return res.end(); }
  if (pathname.startsWith("/api/")) { try { await api(req, res, pathname, requestUrl); } catch (error) { console.error(error); send(res, 500, { error: error.message || "Server xətası" }); } return; }
  if (pathname.startsWith("/media/")) { const file = path.resolve(uploadRoot, path.basename(pathname)); if (!file.startsWith(uploadRoot)) return send(res, 403, "Forbidden"); fs.readFile(file, (error, data) => error ? send(res, 404, "Not found") : (res.writeHead(200, headers({ "Content-Type": types[path.extname(file)] || "application/octet-stream", "Cache-Control": "public, max-age=31536000, immutable" })), res.end(data))); return; }
  const relative = pathname === "/" ? "index.html" : pathname.replace(/^\//, ""); const file = path.resolve(staticRoot, relative); if (!file.startsWith(staticRoot)) return send(res, 403, "Forbidden"); fs.readFile(file, (error, data) => error ? send(res, 404, "Not found") : (res.writeHead(200, headers({ "Content-Type": types[path.extname(file)] || "application/octet-stream" })), res.end(data)));
});
server.listen(port, "0.0.0.0", () => console.log(`Yerli server: ${publicUrl}`));
