CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, identifier TEXT NOT NULL UNIQUE, identifier_type TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'buyer', status TEXT NOT NULL DEFAULT 'active', profile TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires_at BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);
CREATE TABLE IF NOT EXISTS otp_challenges (identifier TEXT PRIMARY KEY, code_hash TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, expires_at BIGINT NOT NULL, requested_at BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS stores (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL UNIQUE REFERENCES users(id), name TEXT NOT NULL, city TEXT NOT NULL, phone TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, store_id TEXT NOT NULL REFERENCES stores(id), title TEXT NOT NULL, category TEXT NOT NULL, price_minor BIGINT NOT NULL CHECK(price_minor > 0), stock INTEGER NOT NULL CHECK(stock >= 0), status TEXT NOT NULL DEFAULT 'pending', details TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS products_catalog ON products(status, category);
CREATE INDEX IF NOT EXISTS products_store ON products(store_id);
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), request_key TEXT NOT NULL, request_hash TEXT NOT NULL, subtotal_minor BIGINT NOT NULL, shipping_minor BIGINT NOT NULL, total_minor BIGINT NOT NULL, customer TEXT NOT NULL, shipping TEXT NOT NULL, payment_method TEXT NOT NULL, payment_status TEXT NOT NULL, payment_session TEXT, checkout_url TEXT, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(user_id, request_key));
CREATE INDEX IF NOT EXISTS orders_user ON orders(user_id, created_at);
CREATE TABLE IF NOT EXISTS shipments (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), store_id TEXT NOT NULL REFERENCES stores(id), shipping_minor BIGINT NOT NULL, subtotal_minor BIGINT NOT NULL, status TEXT NOT NULL, stock_released INTEGER NOT NULL DEFAULT 0, tracking TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS shipments_store ON shipments(store_id, order_id);
CREATE TABLE IF NOT EXISTS order_items (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), shipment_id TEXT NOT NULL REFERENCES shipments(id), product_id TEXT NOT NULL REFERENCES products(id), store_id TEXT NOT NULL REFERENCES stores(id), title TEXT NOT NULL, quantity INTEGER NOT NULL CHECK(quantity > 0), unit_price_minor BIGINT NOT NULL, variant TEXT NOT NULL DEFAULT '{}');
CREATE INDEX IF NOT EXISTS items_order ON order_items(order_id);
CREATE TABLE IF NOT EXISTS webhook_events (id TEXT PRIMARY KEY, event_type TEXT NOT NULL, processed_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY, user_id TEXT, action TEXT NOT NULL, target_id TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS media (path TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), size INTEGER NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS legacy_imports (source_hash TEXT PRIMARY KEY, source_name TEXT NOT NULL, payload TEXT NOT NULL, imported_at TEXT NOT NULL);
